version: "3"

networks:
  treasury:

services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      - mongodb
    env_file:
      - ./api/.env
    restart: always
    volumes:
      - ./api/src:/app/src
    networks:
      - treasury
  www:
    container_name: www
    build:
      context: ./www
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    command: npm start
    depends_on:
      - mongodb
      - api
    restart: always
    volumes:
      - ./www/src:/app/src
    networks:
      - treasury
  mongodb:
    container_name: mongodb
    image: mongo:4.2.7-bionic
    ports:
      - "27017:27017"
    env_file:
      - ./api/.env
    restart: always
    networks:
      - treasury
