version: "3"

networks:
  treasury:

services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    env_file:
      - ./api/.env
    restart: always
    networks:
      - treasury
  www:
    container_name: www
    build:
      context: ./www
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - api
    restart: always
    networks:
      - treasury
  mongodb:
    container_name: mongodb
    image: mongo:4.2.7-bionic
    ports:
      - "27017:27017"
    env_file:
      - ./api/.env
    restart: always
    networks:
      - treasury
